# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
development:
  adapter: postgresql
  encoding: unicode
  database: treebook
  username: postgres
  password: postgres
  host: localhost
  timeout: 3000
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: tree_book_test
  username: postgres
  password: postgres
  host: localhost
  timeout: 3000
  pool: 5
